# Generated by Django 4.1.13 on 2026-03-16 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached', models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Reached', 'Reached')], default='Not Contacted', max_length=20)),
                ('partnership_type', models.CharField(blank=True, choices=[('Strategic', 'Strategic'), ('Referral', 'Referral'), ('Integration', 'Integration')], max_length=50, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], max_length=20, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('point_of_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=20)),
                ('is_manual', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=255)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='partnership_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('reached', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='scraper.partnership')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('contacted', 'Contacted'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='interested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='scraper.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('opportunity', 'user')},
            },
        ),
    ]
