# Generated by Django 4.1.13 on 2026-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('inbound', 'Interested'), ('outbound', 'Contacted'), ('events', 'Applied'), ('institutional', 'Rejected'), ('internal', 'Withdrawn')], default='inbound', max_length=20),
        ),
    ]
