# Generated by Django 5.2.7 on 2025-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
