# Generated by Django 4.1.13 on 2026-02-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='reached',
            field=models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Reached', 'Reached')], default='Not Contacted', max_length=20),
        ),
    ]
