# Generated by Django 4.1.13 on 2026-02-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_partnership_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='partnerships_pdfs/'),
        ),
    ]
