# Generated by Django 4.1.13 on 2026-02-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_partnership_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='pdf_file',
        ),
    ]
