# Generated by Django 4.1.13 on 2026-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_partnership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('events', 'Events'), ('institutional', 'Institutional'), ('internal', 'Internal')], max_length=20, null=True),
        ),
    ]
