# Generated by Django 4.1.13 on 2026-02-19 06:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_partnership_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Kenya', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnership',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
