# Generated by Django 4.1.13 on 2026-02-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_opportunity_country_alter_partnership_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='partnership',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], max_length=20, null=True),
        ),
    ]
