# Generated by Django 4.1.13 on 2026-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_remove_partnership_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
