# Generated by Django 5.2.12 on 2026-03-23 05:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_opportunity_created_at_opportunity_submission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
