# Generated by Django 5.2.12 on 2026-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_opportunity_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
