# Generated by Django 4.1.13 on 2026-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_partnership_comment_alter_partnership_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='reached',
            field=models.CharField(max_length=50),
        ),
    ]
