# Generated by Django 5.2.12 on 2026-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_opportunity_source_opportunity_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='source',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='source_url',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
