# Generated by Django 4.1.13 on 2026-02-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_partnership_email_partnership_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='notes',
        ),
    ]
