# Generated by Django 4.1.13 on 2026-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_remove_partnership_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='partnership_pdfs/'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
