# Generated by Django 4.1.13 on 2026-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_partnership_pdf_file_alter_opportunity_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='pdf_title',
            field=models.CharField(blank=True, help_text='Custom name for the PDF document', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='partnership_type',
            field=models.CharField(blank=True, choices=[('Strategic', 'Strategic'), ('Referral', 'Referral'), ('Integration', 'Integration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='reached',
            field=models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Reached', 'Reached')], default='Not Contacted', max_length=20),
        ),
    ]
