# Generated by Django 4.1.13 on 2026-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_partnership_pdf_title_alter_partnership_meeting_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
