# Generated by Django 4.1.13 on 2026-02-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_partnership_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='pdf_title',
        ),
        migrations.CreateModel(
            name='PartnershipPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='partnership_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='scraper.partnership')),
            ],
        ),
    ]
